"""empty message

Revision ID: d4921fba054f
Revises: 5598054d948f
Create Date: 2019-05-29 16:33:23.975758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4921fba054f'
down_revision = '5598054d948f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'name')
    # ### end Alembic commands ###
